### ISSUE TITLE
Candidate generator et al default functions should have names

### ISSUE THREAD

**Issue by swflint** [zkry/p-search#56]
I'm trying to debug an error where some files are causing p-search to break.  Because the callbacks I'm interested in are lambdas, it's hard to debug the existing implementation or make changes as I try to run the code.

**Comment by swflint** [comment]
The error I noticed was an error in a separate library.  That said, giving the provided, default functions names does seem like a good idea.

**Comment by zkry** [comment]
Good idea. I moved out the filesystem candidate generator's functions along with others. I could definitely help locating the error too. One function that I feel could easily break depending on the file-type is `p-search-document-preview` since it calls `set-auto-mode`, which does open a big can of worms.

**Comment by swflint** [comment]
It was a feature interaction with a buggy version of parsebib.  Updating that library fixed it.
